name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Обновили до v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # Обновили до v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        uses: softprops/action-gh-release@v2 # Обновили до v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # Обновили до v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: Oraxen-Plugin
          path: build/libs/*.jar
